### ISSUE TITLE
Stable API not working anymore

### ISSUE THREAD

**Issue by jezs00** [jezs00/pycasso#12]
Getting the following issue from code that previously worked:

Traceback (most recent call last):
  File "E:\Documents\GitHub\pycasso\run.py", line 26, in <module>
    instance.run()
  File "E:\Documents\GitHub\pycasso\pycasso.py", line 344, in run
    image_base = self.load_stability_image(prompt, fetch_width, fetch_height,
  File "E:\Documents\GitHub\pycasso\pycasso.py", line 188, in load_stability_image
    image = stability_provider.get_image_from_string(prompt, fetch_height, fetch_width)
  File "E:\Documents\GitHub\pycasso\provider.py", line 92, in get_image_from_string
    for resp in answers:
  File "E:\Documents\GitHub\pycasso\venv\lib\site-packages\stability_sdk\client.py", line 363, in generate
    artifact_ts = [
  File "E:\Documents\GitHub\pycasso\venv\lib\site-packages\stability_sdk\client.py", line 364, in <listcomp>
    generation.ArtifactType.Name(artifact.type)
  File "E:\Documents\GitHub\pycasso\venv\lib\site-packages\google\protobuf\internal\enum_type_wrapper.py", line 64, in Name
    raise ValueError('Enum {} has no name defined for value {!r}'.format(
ValueError: Enum ArtifactType has no name defined for value 8

**Comment by jezs00** [comment]
Appears to be using credits, so it should be returning an image. Code still matches code example.
