### ISSUE TITLE
Installation on RasPi Zero GRPCIO fix not working

### ISSUE THREAD

**Issue by DanielL99** [jezs00/pycasso#51]
Hi there, i've tried to install pycasso on a Raspberry Pi Zero W with the latest Raspberry Pi OS.

After updating all packages I used `sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)"` and installed option 1. I got the expected result:
```
Collecting grpcio==1.48.1
  Downloading grpcio-1.48.1.tar.gz (22.0 MB)
     |████████████████████████████████| 22.0 MB 10 kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wgtas6e2/grpcio_06b9c5798fe445afa887e45b58b51265/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wgtas6e2/grpcio_06b9c5798fe445afa887e45b58b51265/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-m480ggu6
         cwd: /tmp/pip-install-wgtas6e2/grpcio_06b9c5798fe445afa887e45b58b51265/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wgtas6e2/grpcio_06b9c5798fe445afa887e45b58b51265/setup.py", line 263, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-wgtas6e2/grpcio_06b9c5798fe445afa887e45b58b51265/setup.py", line 219, in check_linker_need_libatomic
        cpp_test = subprocess.Popen(
      File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.9/subprocess.py", line 1698, in _execute_child
        and os.path.dirname(executable)
      File "/usr/lib/python3.9/posixpath.py", line 152, in dirname
        p = os.fspath(p)
    TypeError: expected str, bytes or os.PathLike object, not list
    ----------------------------------------
```

After that I installed option 5. and after 3 hours I got the following long error:
[Log.txt](https://github.com/jezs00/pycasso/files/10957459/Log.txt)

I can not set my DALL-E API Key, because of the missing GRPCIO.
Did I do something wrong or is there a workaround to set my API Key without using option 7?

**Comment by jezs00** [comment]
This is likely related to #48. Zero just won't work with grpcio on an
operating system level as far as I can tell.

The good news is that it's not required by dalle, only SD, and within
pycasso we should be able to disable Keychain.

Try to edit .config and make sure "use_keychain" is set to false and try
setting keys again.

The bad news is it's possible that the installation cascade is affected by
the failure of grpcio to install. That's going to take more work to try and
fix and I might have to write a custom install for zeros. The advice I gave
for now in #48 was to run the minimal pycasso install, then try and install
the packages in requirements.txt one by one with pip3.
